-- Explpore AlL Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;
-- Explore  All columns in the Database 
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
 --Explore All countries come from
 select distinct country from gold.dim_customer;
 -- ERxplore All categories 'The major Divisions'
 select distinct category,subcategory from gold.dim_products;

-- find the date of the first and last ordder 
select  
min(order_date) as first_order,
max(order_date) as lasr_order,
datediff(year,min(order_date),max(order_date)) as order_range
from gold.fact_sales;

-- find the Total  sales
select 'Total Sales' as measure_name, sum(sales_amount) from gold.fact_sales
-- find how many items are sold 
union all
select 'Total sold', sum(s.quantity) from gold.fact_sales s

-- find the average selling price
union all
select 'Average price' , AVG(s.price)  from gold.fact_sales s
-- find the total number of orders 
union all
select 'Total Nr. orders', count(distinct order_number) from gold.fact_sales 
-- find the total number of product
union all
select  'Total Nr. product', count(distinct p.product_key)  from gold.dim_products p
-- find the  total number of customers 
union all
select 'Total Nr. customer', count(distinct c.customer_key)  from gold.dim_customer c
-- find the total number of customers that has placed an order
union all
select 'total nr. customer place order' , count(s.customer_key) from gold.fact_sales s ;
-- find total customer by countries 
select c.country, count( c.customer_key) 
from gold.dim_customer c
group by c.country
order by count( c.customer_key) 
-- find total customers by gender
SELECT c.gender, count(c.customer_key) as total_gender from  gold.dim_customer c
group by c.gender
order by total_gender
-- find total products by category 
select p.category, count(p.product_key) total_prod from  gold.dim_products p
group by p.category
order by total_prod desc
-- what is the average costs in each category?
select p.category, AVG(p.product_cost) as average_cost from gold.dim_products p
group by p.category
order by average_cost desc


-- what is the total revenue generated for each category?
select p.category, sum(s.sales_amount) as total_revenue from gold.fact_sales s
left join gold.dim_products p
on p.product_key = s.product_key
group by p.category
order by total_revenue  desc
-- find total revenue is generated by each customer
select c.customer_key, c.first_name, c.last_name, sum(s.sales_amount)  as sum_sales from gold.fact_sales s
left join gold.dim_customer c
on c.customer_key = s.customer_key
group by c.customer_key, c.first_name, c.last_name
order by sum_sales desc
-- what is the  distribution of sold items across countries 

-- Calcualte the total sales per month 
-- and the running total of sales over time 
SELECT
order_date,total_sales,
sum(total_sales) over (order by order_date) as running_total_sales 
FROM (
select DATETRUNC(year, order_date) as order_date, sum(sales_amount)as total_sales, AVG(price) as avg_price
from gold.fact_sales
where order_date IS NOT NULL
GROUP BY DATETRUNC(year,order_date)) t
;
/* Analyze the yearly performance of products by comparing thier sales to both the average
sales performance of the product and the previous year's sales */
WITH yearly_product_sales AS (
	select
	year(s.order_date) as order_year , p.product_name as product_name,sum( s.sales_amount) as current_sales
	from gold.fact_sales s
	LEFT JOIN gold.dim_products  p
	on p.product_key = s.product_key
	where s.order_date IS NOT NULL
	group by year(s.order_date), p.product_name)

SELECT 
	order_year, product_name, current_sales,
	AVG(current_sales) OVER ( PARTITION BY product_name) AS avg_sales,
	current_sales - AVG(current_sales) OVER ( PARTITION BY product_name) AS diff_avg,
	CASE WHEN current_sales - AVG(current_sales) OVER ( PARTITION BY product_name) > 0 THEN 'Above Avg'
		WHEN current_sales - AVG(current_sales) OVER ( PARTITION BY product_name) <0 THEN 'Below Avg'
		ELSE 'Avg'
	END avg_change,
	LAG (current_sales) OVER ( PARTITION BY product_name ORDER BY order_year) AS py_sales,
	current_sales - LAG (current_sales) OVER ( PARTITION BY product_name ORDER BY order_year) as diff_py,
	CASE WHEN current_sales - LAG (current_sales) OVER ( PARTITION BY product_name ORDER BY order_year) > 0 THEN 'INCREASE'
		 WHEN current_sales - LAG (current_sales) OVER ( PARTITION BY product_name ORDER BY order_year) < 0 THEN 'DECREASE'
		 ELSE 'No Change' 
	END py_change
FROM yearly_product_sales
order by  product_name, order_year;
 -- which categories contribute the most to overall sales ?
 with category_sales as (
select 
p.category, sum( s.sales_amount) total_sales
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.category)

 select category, total_sales
, sum(total_sales) over () overall_sales,
concat(round((cast( total_sales as FLOAT)/ sum(total_sales) over())*100,2),'%') as percentage_of_total
from category_sales 
;
-- product segmentation 
--
with product_segments as (
select
product_key, product_name, product_cost,
case when product_cost < 100 then 'Below 100'
	when product_cost between 100 and 500 then '100-500'
	when product_cost between 500 and 1000 then '500-1000'
	else 'Above 1000'
end cost_range
from gold.dim_products)

select cost_range,
count(product_key) as total_products
from product_segments
group by cost_range 
order by total_products desc 
/* Group customers into three segments based on their spending behavior:
	- VIP: Customers with at least 12 months of history but spending $5000.
	- Regular: Customer with at least 12 months of history but spending $5000 or less.
	- New: Customer with a lifespan less than 12 months.
And find total number of customers by each group */

with customer_spending as (
select 
c.customer_key,
sum(s.sales_amount) as total_spending,
min( s.order_date) as first_order,
max(s.order_date) as last_order,
datediff(month, min( s.order_date),max(s.order_date)) as lifespan

from gold.fact_sales s
left join gold.dim_customer c
on s.customer_key = c.customer_key
group by c.customer_key)

select 
customer_segment,
count(customer_key)
 from(
	select  
	customer_key, 
	case when lifespan >= 12 and total_spending >5000 then 'VIP'
		when lifespan >= 12 and  total_spending <= 5000 then  'Regular'
		else  'New'
	end customer_segment
from customer_spending) t
group by  customer_segment;
